version: 2.1

jobs:
  rspec:
    parameters:
      ruby-version:
        type: string
      gemfile:
        type: string
      database:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>-node-browsers
        environment:
          DB: << parameters.database >>
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_DATABASE: avatax
          MYSQL_USER: avatax
          MYSQL_PASSWORD: password
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: 'avatax'
          POSTGRES_PASSWORD: 'password'
          POSTGRES_DB: 'avatax'
    steps:
      - checkout
      - when:
          condition:
            equal: ["mysql", << parameters.database >>]
          steps:
            - run:
                name: Configure MySQL2
                # Hack to set environment variable for later steps https://circleci.com/docs/2.0/env-vars/#example-configuration-of-environment-variables
                command: echo 'export DATABASE_URL="mysql2://avatax:password@127.0.0.1/avatax"' >> $BASH_ENV
      - when:
          condition:
            equal: ["postgres", << parameters.database >>]
          steps:
            - run:
                name: Configure Postgres
                command: echo 'export DATABASE_URL="postgresql://avatax:password@127.0.0.1/avatax"' >> $BASH_ENV
      - run:
          name: Configure bundler
          command: bundle config --local path '~/.bundle'
      - run:
          name: Select Gemfile
          command: cp gemfiles/<< parameters.gemfile >>.gemfile gemfiles/ci.gemfile
      - restore_cache:
          keys:
            - bundler-v10-<< parameters.ruby-version >>-<< parameters.gemfile >>-{{ checksum "gemfiles/ci.gemfile" }}
            - bundler-v10-<< parameters.ruby-version >>-<< parameters.gemfile >>
      - run:
          name: Install dependencies
          command: bundle install --gemfile=gemfiles/ci.gemfile
      - save_cache:
          key: bundler-v10-<< parameters.ruby-version >>-<< parameters.gemfile >>-{{ checksum "gemfiles/ci.gemfile" }}
          paths:
            - "~/.bundle"
      - run:
          name: Setup test app
          command: bundle exec --gemfile=gemfiles/ci.gemfile rake test_app
      - run:
          name: Run RSpec
          command: bundle exec --gemfile=gemfiles/ci.gemfile rake spec
workflows:
  all-specs:
    jobs:
      - rspec:
          matrix:
            parameters:
              database:
                - mysql
                - postgres
              gemfile:
                - spree_4_2
                - spree_4_3
              ruby-version:
                - "3.0"
                - "2.7"




